apiVersion: v1
kind: PersistentVolume
metadata:
  name: logo-detect-volume
  namespace: logo-detect
  labels:
    type: k8s-hostpath
spec:
  storageClassName: k8s-hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/k8s/yolov5-huynt"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logo-detect-logs-volume
  namespace: logo-detect
  labels:
    type: k8s-hostpath
spec:
  storageClassName: k8s-hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/k8s/logs/logodetect"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    logo.detect.service: logodetect
  name: logo-detect-claim
  namespace: logo-detect
spec:
  storageClassName: k8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    logo.detect.service: logodetect
  name: logo-detect-logs-claim
  namespace: logo-detect
spec:
  storageClassName: k8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

