apiVersion: v1
kind: Service
metadata:
  name: ksport2epz
  namespace: logo-detect
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: ksport2epz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksport2epz
  namespace: logo-detect
spec:
  selector:
    matchLabels:
      app: ksport2epz
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ksport2epz
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/udp-multicast-conf@vlan320
    spec:
      nodeSelector:
        heavy: "1"
      containers:
      - name: ksport2epz
        image: 172.27.223.7:32000/logodetect:latest
        imagePullPolicy: Always
        args:
          - python3
          - detectUDP.py
          - --weights 
          - weights/best.onnx
          - --source
          - udp://
          - --nosave
        volumeMounts:
        - name: logs-claim
          mountPath: /usr/src/app/log
        - name: logs-claim
          mountPath: /usr/src/app/runs
        resources:
          requests:
            memory: "500Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "2"
      volumes:
      - name: logs-claim
        persistentVolumeClaim:
          claimName: logo-detect-logs-claim